"""FRIDAY Backend — Pydantic models for Chat."""
from pydantic import BaseModel, Field
from typing import Optional, Literal


class AskRequest(BaseModel):
    """Input payload for /ask endpoint."""
    question: str = Field(..., min_length=1, description="User query or prompt")


class AskResponse(BaseModel):
    """Minimal output payload for /ask endpoint."""
    answer: str = Field(..., description="Response text generated by the LLM")
    model_used: str = Field(..., description="The final LLM model used for execution")
    agent_used: Optional[str] = Field("AcademicAgent", description="The specialized agent selected by Controller AI")



class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="User message content")
    session_id: Optional[str] = Field(None, description="Conversation session ID")
    use_rag: bool = Field(True, description="Query Obsidian vault via RAG")
    use_web_search: bool = Field(False, description="Enable live Tavily web search")
    model: Optional[str] = Field(None, description="Override model (defaults to config)")


class ToolCallResult(BaseModel):
    tool_name: str
    status: Literal["completed", "failed"]
    result_summary: Optional[str] = None


class ChatResponse(BaseModel):
    session_id: str
    role: Literal["assistant"] = "assistant"
    content: str
    tool_calls: list[ToolCallResult] = []
    model: str
    model_used: Optional[str] = None


class StreamChunk(BaseModel):
    """A single SSE streaming chunk."""
    type: Literal["token", "tool_call", "done", "error", "model_info"]
    content: Optional[str] = None
    tool_name: Optional[str] = None
    session_id: Optional[str] = None
    model_used: Optional[str] = None
    task_type: Optional[str] = None
    error: Optional[str] = None
